### PR TITLE
PLEASE USE ('fs').promises;

### PR DESCRIPTION
**Pull request by Kian738**
I cant use minify on my replit projects and idk if this works but this worked for me

### CODE REVIEW

**Comment by coderaiser** [comment]
It looks like a old node version  in replit, you can try this https://replit.com/talk/ask/change-node-version/5924 to update to latest supported version of `node.js`.

**Comment by Kian738** [comment]
Yeah replit is using node 12.2 but undone have any permissions to update node and when I change the alias nodemon keeps using v12

**Comment by coderaiser** [comment]
Have you tried to use [nvm](https://github.com/nvm-sh/nvm)?

**Comment by Kian738** [comment]
nvm I got it working 
I had to set the node version in package.json

**Pull request closed without merging**
